'use server'
/**
 * CLIENT SERVER ACTIONS — Invites, project assignment, access control
 * ─────────────────────────────────────────────────────────────────────────────
 * All mutations are admin-only. revalidatePath('/clients') keeps the list fresh.
 *
 * WHY THE SERVICE ROLE: creating an auth user and promoting them to the
 * `client` role cannot be done as the signed-in admin — inviting is an Auth
 * Admin API call, and the promotion has to happen before the client ever logs
 * in. Doing it here, rather than by reading a role out of raw_user_meta_data
 * in handle_new_auth_user, is deliberate: user metadata is writable by the
 * signing-up user, so a trigger that trusted it would let anyone self-register
 * as an admin. See migration 014's header.
 * ─────────────────────────────────────────────────────────────────────────────
 */
import { revalidatePath } from 'next/cache'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { getSiteUrl } from '@/lib/site-url'

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/

async function requireAdmin() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')
  const { data: profile } = await supabase
    .from('users').select('role').eq('id', user.id).single()
  if (profile?.role !== 'admin') throw new Error('Admin only.')
  return supabase
}

/**
 * Where both invite and recovery emails land.
 *
 * /auth/confirm, NOT /auth/callback: these emails are generated by the admin
 * (or by the service role on the admin's behalf), so no PKCE code verifier
 * exists in the recipient's browser and there is no `?code=` for them to
 * redeem. /auth/confirm verifies a token hash instead — see its header.
 *
 * The Supabase email templates build the actual link themselves from
 * `{{ .TokenHash }}` (docs/client-invite-email-templates.md). This value is
 * still sent as `redirectTo` so it is the allowlisted destination on record
 * and is available to the template as `{{ .RedirectTo }}`.
 */
function passwordSetupUrl() {
  return `${getSiteUrl()}/auth/confirm?next=/set-password`
}

// ── Invite ────────────────────────────────────────────────────────────────────

/**
 * Invite a client by email and optionally assign them to projects up front.
 * Sends Supabase's invite email (delivered via the Resend SMTP settings), which
 * lands the client on /set-password.
 */
export async function inviteClient(formData: FormData) {
  await requireAdmin()

  const email      = String(formData.get('email') ?? '').trim().toLowerCase()
  const name       = String(formData.get('name')  ?? '').trim()
  const projectIds = formData.getAll('projectIds').map(String).filter(Boolean)

  if (!EMAIL_RE.test(email)) throw new Error('Enter a valid email address.')
  if (!name)                 throw new Error('Enter the client’s name.')

  const admin = createAdminClient()

  // Refuse before calling the Auth API so the admin gets a useful message
  // rather than Supabase's generic "email already registered".
  const { data: existing } = await admin
    .from('users').select('id, role').eq('email', email).maybeSingle()

  if (existing) {
    throw new Error(
      existing.role === 'client'
        ? `${email} has already been invited as a client.`
        : `${email} already has a ${existing.role} account in the portal.`,
    )
  }

  const { data: invited, error: inviteError } = await admin.auth.admin.inviteUserByEmail(
    email,
    { redirectTo: passwordSetupUrl(), data: { full_name: name } },
  )

  if (inviteError || !invited?.user) {
    throw new Error(inviteError?.message ?? 'Could not send the invite.')
  }

  const userId = invited.user.id

  // handle_new_auth_user creates the public.users row as an unapproved
  // provider. Promote it. Clients are pre-approved because an admin invited
  // them — they should never sit in the approval queue.
  const { data: promoted, error: promoteError } = await admin
    .from('users')
    .update({ role: 'client', name, approved: true })
    .eq('id', userId)
    .select('id')
    .maybeSingle()

  if (promoteError) throw new Error(promoteError.message)

  // Defensive: if the trigger hasn't landed yet, write the row ourselves.
  if (!promoted) {
    const { error: upsertError } = await admin
      .from('users')
      .upsert({ id: userId, email, name, role: 'client', approved: true })
    if (upsertError) throw new Error(upsertError.message)
  }

  if (projectIds.length > 0) {
    const { error: memberError } = await admin.from('project_members').insert(
      projectIds.map(project_id => ({
        project_id,
        user_id:         userId,
        role_in_project: 'client',
      })),
    )
    if (memberError) throw new Error(memberError.message)
  }

  revalidatePath('/clients')
  revalidatePath('/projects')
}

/**
 * Send a fresh link to a client who never finished setup — or whose invite
 * link was consumed by a corporate mail scanner before they clicked it.
 * Uses the recovery flow because the auth user already exists by this point.
 *
 * WHY THE ADMIN CLIENT AND NOT THE SIGNED-IN ADMIN'S SERVER CLIENT — this is
 * load-bearing, please do not "simplify" it back:
 *
 * `resetPasswordForEmail` only mints a PKCE code challenge when the client's
 * `flowType` is `'pkce'` (GoTrueClient.resetPasswordForEmail), and it stashes
 * the matching verifier in that client's own storage. `@supabase/ssr`
 * hardcodes `flowType: 'pkce'`, so calling this on the server client wrote the
 * verifier into THE ADMIN'S cookie jar — meaning the link in the client's
 * inbox could only ever be redeemed by the admin's browser. That is the bug.
 *
 * `createAdminClient()` builds a plain `@supabase/supabase-js` client, whose
 * `flowType` defaults to `'implicit'` and which runs with
 * `persistSession: false`. No challenge is generated, no verifier is written
 * anywhere, and the email carries a token hash that /auth/confirm can verify
 * for whoever opens it. Supabase still delivers the mail through the
 * configured SMTP (Resend) either way.
 */
export async function resendClientInvite(userId: string) {
  await requireAdmin()

  const admin = createAdminClient()
  const { data: client, error } = await admin
    .from('users').select('email, role').eq('id', userId).single()

  if (error)                   throw new Error(error.message)
  if (client.role !== 'client') throw new Error('That user is not a client.')

  const { error: sendError } = await admin.auth.resetPasswordForEmail(
    client.email,
    { redirectTo: passwordSetupUrl() },
  )
  if (sendError) throw new Error(sendError.message)
}

// ── Project assignment ────────────────────────────────────────────────────────

/**
 * Replace the set of projects a client can see. Clients are not limited to one
 * project — this takes the full desired list and reconciles.
 */
export async function setClientProjects(userId: string, projectIds: string[]) {
  await requireAdmin()

  const admin = createAdminClient()
  const { data: client, error } = await admin
    .from('users').select('id, role').eq('id', userId).single()

  if (error)                    throw new Error(error.message)
  if (client.role !== 'client') throw new Error('That user is not a client.')

  const { data: current, error: currentError } = await admin
    .from('project_members').select('project_id').eq('user_id', userId)
  if (currentError) throw new Error(currentError.message)

  const currentIds = new Set((current ?? []).map(r => r.project_id))
  const desiredIds = new Set(projectIds)

  const toAdd    = [...desiredIds].filter(id => !currentIds.has(id))
  const toRemove = [...currentIds].filter(id => !desiredIds.has(id))

  if (toAdd.length > 0) {
    const { error: addError } = await admin.from('project_members').insert(
      toAdd.map(project_id => ({
        project_id,
        user_id:         userId,
        role_in_project: 'client',
      })),
    )
    if (addError) throw new Error(addError.message)
  }

  if (toRemove.length > 0) {
    const { error: removeError } = await admin
      .from('project_members')
      .delete()
      .eq('user_id', userId)
      .in('project_id', toRemove)
    if (removeError) throw new Error(removeError.message)
  }

  revalidatePath('/clients')
  revalidatePath('/projects')
}

// ── Access control ────────────────────────────────────────────────────────────

/**
 * Cut a client off. Un-approving alone is only an app-level gate — the RLS
 * policies key off project membership, so a revoked client would still be able
 * to reach project data through the API with a live session. Removing the
 * memberships is what actually enforces it.
 */
export async function revokeClientAccess(userId: string) {
  await requireAdmin()

  const admin = createAdminClient()
  const { data: client, error } = await admin
    .from('users').select('id, role').eq('id', userId).single()

  if (error)                    throw new Error(error.message)
  if (client.role !== 'client') throw new Error('That user is not a client.')

  const { error: memberError } = await admin
    .from('project_members').delete().eq('user_id', userId)
  if (memberError) throw new Error(memberError.message)

  const { error: approveError } = await admin
    .from('users').update({ approved: false }).eq('id', userId)
  if (approveError) throw new Error(approveError.message)

  revalidatePath('/clients')
  revalidatePath('/projects')
}

/**
 * Let a revoked client back in. Project access is NOT restored — memberships
 * were deleted on revoke, so they have to be re-assigned deliberately.
 */
export async function restoreClientAccess(userId: string) {
  await requireAdmin()

  const admin = createAdminClient()
  const { error } = await admin
    .from('users').update({ approved: true }).eq('id', userId).eq('role', 'client')
  if (error) throw new Error(error.message)

  revalidatePath('/clients')
}
